Add publish at the end

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -119,3 +119,42 @@ jobs:
             echo "Not the same version. Exit with Failure!";
             exit 1;
           fi
+
+  publish:
+    needs:
+      - package
+      - check_version
+      - test-pypi-publish    
+    runs-on: ubuntu-latest    
+    permissions:
+      id-token: write
+
+    steps:
+      - uses: actions/download-artifact@v4
+        with:
+          name: ${{ env.ARTIFACT }}
+          path: ${{ github.workspace }}/dist/
+
+      - name: Publish to PyPI
+        uses: pypa/gh-action-pypi-publish@release/v1
+        with:
+          packages-dir: ${{ github.workspace }}/dist/
+          verbose: true
+          print-hash: true
+
+      - uses: actions/setup-python@v5
+        with:
+          python-version: ">=3.11" 
+
+      - name: Check install 
+        run: pip install ${{ needs.package.outputs.package_name }}
+
+      - name: Check application version output matches release tag
+        run: |
+          VERSION=$(${{ env.APP_NAME }} version)
+          echo "Check [v$VERSION] == [${{github.event.release.tag_name}}]"
+          if [ "v$VERSION" != "${{github.event.release.tag_name}}" ]; then 
+            echo "Not the same version. Exit with Failure!";
+            exit 1;            
+          fi       
+   
